/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./resources/js/components/ApplicationLogo.vue')['default']
    Avatar: typeof import('./resources/js/components/Avatar.vue')['default']
    Bookmarks: typeof import('./resources/js/components/Bookmarks.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    Checkbox: typeof import('./resources/js/components/Checkbox.vue')['default']
    DangerButton: typeof import('./resources/js/components/DangerButton.vue')['default']
    Dropdown: typeof import('./resources/js/components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/components/DropdownLink.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    GoBackBtn: typeof import('./resources/js/components/GoBackBtn.vue')['default']
    InputError: typeof import('./resources/js/components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/components/Modal.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    NavLink: typeof import('./resources/js/components/NavLink.vue')['default']
    NewPr: typeof import('./resources/js/components/dashboard/NewPr.vue')['default']
    Notifications: typeof import('./resources/js/components/Notifications.vue')['default']
    PrCard: typeof import('./resources/js/components/dashboard/PrCard.vue')['default']
    PrimaryButton: typeof import('./resources/js/components/PrimaryButton.vue')['default']
    QrCode: typeof import('./resources/js/components/QrCode.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/components/ResponsiveNavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./resources/js/components/SecondaryButton.vue')['default']
    TextInput: typeof import('./resources/js/components/TextInput.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
  }
}
